name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print CI status
      run: |
        echo "Attempting to print CI status..."
        CI_STATUS=$(echo "CI status received from 'PolusAI/workflow-inference-compiler'" || echo "Failed to retrieve CI status")
        echo $CI_STATUS
