FROM ubuntu:22.04

# Install miniconda
RUN apt-get update && apt-get install -y wget
RUN CONDA="Mambaforge-Linux-x86_64.sh" && \
    wget --quiet https://github.com/conda-forge/miniforge/releases/latest/download/$CONDA && \
    chmod +x $CONDA && \
    ./$CONDA -b -p /mambaforge && \
    rm -f $CONDA
ENV PATH /mambaforge/bin:$PATH

RUN conda install -c conda-forge -c openbiosim biosimspace
ENV SIRE_DONT_PHONEHOME 1

RUN conda install -c conda-forge gromacs

ADD conversion.py .
ADD Dockerfile_biosimspace .
