import argparse
from pathlib import Path

import json

from .schemas.biobb import config_schemas


parser = argparse.ArgumentParser(prog='main', description='Convert a high-level yaml workflow file to CWL.')
parser.add_argument('--generate_schemas', default=False, action="store_true",
                    help='Generate schemas for the files in config.json (search_paths_wic and search_paths_cwl)')


def generate_config_schemas() -> None:
    """Generate special jsonschemas for the biobb config tags."""
    path = Path('autogenerated/schemas/config_schemas.json')
    path.parent.mkdir(exist_ok=True, parents=True)
    with open(path, mode='w', encoding='utf-8') as f:
        f.write(json.dumps(config_schemas, indent=2))


def main() -> None:
    args = parser.parse_args()
    if args.generate_schemas:
        generate_config_schemas()


if __name__ == '__main__':
    main()
