from pathlib import Path

import json

from .schemas.biobb import config_schemas


def main() -> None:
    path = Path('autogenerated/schemas/config_schemas.json')
    path.parent.mkdir(exist_ok=True, parents=True)
    with open(path, mode='w', encoding='utf-8') as f:
        f.write(json.dumps(config_schemas, indent=2))


if __name__ == '__main__':
    main()
