FROM ubuntu:22.04 as download

# Install miniconda
RUN apt-get update && apt-get install -y wget
RUN CONDA="Miniforge-Linux-x86_64.sh" && \
    wget --quiet https://github.com/conda-forge/miniforge/releases/latest/download/$CONDA && \
    chmod +x $CONDA && \
    ./$CONDA -b -p /miniforge && \
    rm -f $CONDA
ENV PATH /miniforge/bin:$PATH

RUN conda install -c conda-forge wget libarchive
# bsdtar is installed with libarchive; see download_data.sh

ADD Dockerfile_data .
ADD download_data.sh .

RUN ./download_data.sh

# Now copy everything into a minimal alpine linux distro.
# Ideally we would like to use FROM scratch, but we need the `cp` command.
FROM alpine as data

COPY --from=download *.sdf ./
COPY --from=download *.xlsx ./
COPY --from=download Dockerfile_data ./
COPY --from=download download_data.sh ./