
# docker build -f Dockerfile_pose_cluster_filter -t mrbrandonwalker/pose_cluster_filter .

FROM condaforge/miniforge3

RUN conda install -c conda-forge rdkit --yes

RUN conda init bash

COPY pose_cluster_filter.py /

RUN mamba clean --all --yes

ADD Dockerfile_pose_cluster_filter .