steps:

  - extract_pdbbind_refined:
      in:
        # https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html
        # "The query() method uses a slightly modified Python syntax by default.
        # For example, the & and | (bitwise) operators have the precedence of their boolean cousins, and and or.
        # This is syntactically valid Python, however the semantics are different."
        query: '(Kd_Ki == "Kd") and (value < 0.001)'
        max_row: 1 #25 # Use 1 for CI
        convert_Kd_dG: 'True'
        output_pdb_paths: '&pdbbind_pdbs'
        output_sdf_paths: '&pdbbind_sdfs'

  - fix_side_chain:
      scatter: [input_pdb_path]
      in:
        input_pdb_path: '*pdbbind_pdbs'
        output_pdb_path: '&pdbbind_pdbs.pdb'

  - diffdock:
      scatter: [protein_path, ligand_path]
      scatterMethod: dotproduct
      in:
        protein_path: "*pdbbind_pdbs.pdb"
        ligand_path: "*pdbbind_sdfs"
        samples_per_complex: 20 # figure 3 left in DiffDock paper
        inference_steps: 20 # figure S11 in DiffDock paper
        batch_size: 16 # section D.3 in DiffDock paper
        output_files: "&diffdock_poses"

  - rank_diffdock_poses:
      scatter: [diffdock_poses]
      in:
        top_n_confident: 1000 # if only using top_percent_confidence, then set top_n_confident to trivially high number
        # if only want to use top_n_confident, then set top_percent_confidence to 100
        top_percent_confidence: 33 # take top third of most confident poses, see figure 3 right in DiffDock paper
        diffdock_poses: "*diffdock_poses"
        output_poses: "&output_poses"

  - pose_cluster_filter:
      scatter: [predicted_poses]
      in:
        predicted_poses: "*output_poses"
        centroid_cutoff: 5 # if centroid of all poses are within cutoff then only keep most confident pose, requires visual inspection

wic:
  graphviz:
    label: DiffDock

  steps:
    (1, extract_pdbbind_refined):
      wic:
        graphviz:
          label: Extract PDBbind Data
    (2, fix_side_chain):
      wic:
        graphviz:
          label: Fix Side Chains
    (3, diffdock):
      wic:
        namespace: gpu
        graphviz:
          label: Executing DiffDock
    (4, rank_diffdock_poses):
      wic:
        graphviz:
          label: Rank all poses
    (5, pose_cluster_filter):
      wic:
        graphviz:
          label: Cluster poses