FROM condaforge/mambaforge
# NOT mambaforge-pypy3 (pandas & rdkit are incompatible with pypy)

RUN mamba install -c conda-forge "python=3.7.*" pandas rdkit openpyxl xorg-libxrender

ADD generate_conformers.py .
ADD python_cwl_driver.py .
ADD workflow_types.py .

ADD Dockerfile_generate_conformers .
