# docker build -f Dockerfile_pdbbind_refined -t mrbrandonwalker/pdbbind_refined_v2020 .

FROM condaforge/mambaforge
# NOT mambaforge-pypy3 (pandas is incompatible with pypy)

RUN mamba install -c conda-forge pandas

ADD generate_pdbbind_complex.py /generate_pdbbind_complex.py
ADD Dockerfile_pdbbind_refined /Dockerfile_pdbbind_refined
