FROM condaforge/mambaforge
# NOT mambaforge-pypy3 (pandas & rdkit & mdtraj are incompatible with pypy)

# Install requirements
RUN apt-get update && apt-get install -y wget git

# Create environment
# Since python 3.10 is already installed in the base image condaforge/mambaforge, 
# See https://github.com/zhenglz/onionnet#installation 
# OnionNet uses sklearn.externals.joblib which is removed in sklearn 0.23
# RUN mamba install -y python=3.7 Doesn't work
RUN mamba create -n py37 python=3.7

# Activate the conda environment
SHELL ["conda", "run", "-n", "py37", "/bin/bash", "-c"]
RUN echo "source activate py37" > ~/.bashrc
ENV PATH /opt/conda/envs/env/bin:$PATH

# Install the required packages
RUN mamba install -c conda-forge scipy numpy pandas "scikit-learn<0.23" mdtraj openbabel tensorflow -y

# cleanup
RUN apt-get clean
RUN mamba clean --all --yes

# Install onionnet
RUN git clone https://github.com/zhenglz/onionnet.git

# Download models
## the default model of onionnet-v1 in github repo is not correct, the actually size is around 600 MB. 
## The authors provided a google drive link to download it, 
## but their command wget "https://drive.google.com/uc?export=download&id=1cwJN44TgaVBWYEEb_SGU5JBJp6WbFdM1" -O "CNN_final_model_weights.h5" is not working.
RUN cd /onionnet/models && rm CNN_final_model_weights.h5 && wget -nv --no-clobber https://huggingface.co/ndonyapour/OnionNet-V1/resolve/main/CNN_final_model_weights.h5
ADD Dockerfile_onionnet .