FROM condaforge/miniforge3
# NOT miniforge-pypy3 (The build process is incompatible with pypy)

# RUN conda install -c conda-forge vina

RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/ccsb-scripps/AutoDock-Vina.git

# Prevent being prompted for geographical region
ARG DEBIAN_FRONTEND=noninteractive

# Build vina binary
RUN apt-get update && apt-get install -y build-essential libboost-all-dev swig
RUN cd AutoDock-Vina/build/linux/release && make
# Since there is no make install, manually copy vina
RUN cp AutoDock-Vina/build/linux/release/vina /usr/bin/

# Build and install python bindings
RUN conda install -c conda-forge numpy boost-cpp swig
RUN cd AutoDock-Vina/build/python && python setup.py build install

ADD Dockerfile_autodock_vina .
