FROM condaforge/miniforge
# NOT mambaforge-pypy3 (pandas & rdkit are incompatible with pypy)

RUN mamba install -c conda-forge pandas rdkit openpyxl xorg-libxrender

ADD generate_conformers.py .
ADD Dockerfile_generate_conformers .
