# docker build -f Dockerfile_extract_ligand_protein -t mrbrandonwalker/extract_ligand_protein .
FROM condaforge/mambaforge
# NOT mambaforge-pypy3 (mdanalysis is incompatible with pypy)
RUN mamba install mdanalysis

ADD extract_ligand_protein.py .
ADD Dockerfile_extract_ligand_protein .