FROM condaforge/miniforge3
# NOT mambaforge-pypy3 (pandas & rdkit & mdtraj are incompatible with pypy)

# Scikit-learn 1.0.2 is only compatible with 3.6 < python < 3.11
RUN mamba install -y python=3.10
# Install requirements
RUN apt-get update && apt-get install -y wget git
RUN mamba install -c conda-forge openbabel numpy pandas mdtraj biopandas -y
# model saved required scikit-learn==1.0.2
RUN pip install -U scikit-learn==1.0.2 rdkit-pypi

# cleanup
RUN apt-get clean
RUN mamba clean --all --yes
RUN pip cache purge

# Install OnionNet-SFCT
RUN git clone https://github.com/misterbrandonwalker/OnionNet-SFCT.git
WORKDIR /OnionNet-SFCT

# Download models
RUN mkdir -p data && cd data && wget -nv --no-clobber https://huggingface.co/cyangNYU/OnionNet-SFCT-final-model/resolve/main/sfct_std_final.model

ADD Dockerfile_onionnet-sfct .
