FROM condaforge/mambaforge
# NOT mambaforge-pypy3 (pandas & rdkit & mdtraj are incompatible with pypy)

# Install requirements
RUN apt-get update && apt-get install -y wget git

# Create environment
# Since python 3.10 is already installed in the base image condaforge/mambaforge, 
# if not specify the python version requirement, python version will has conflict with the openbabel <3.0.
#0 23.40 Pinned packages:
#0 23.40   - python 3.10.*
#0 23.40 The following packages are incompatible
#0 23.40 └─ openbabel <3.0  is installable with the potential options
#0 23.40    ├─ openbabel 2.4.1 would require
#0 23.40    │  └─ python >=2.7,<2.8.0a0 , which can be installed;
#0 23.40    ├─ openbabel 2.4.1 would require
#0 23.40    │  └─ python >=3.6,<3.7.0a0 , which can be installed;
#0 23.40    └─ openbabel 2.4.1 would require
#0 23.40       └─ python >=3.7,<3.8.0a0 , which can be installed.
# So, explicitly downgrade to python=3.7.*
RUN mamba install -c conda-forge "python=3.7.*" "openbabel<3.0" numpy pandas mdtraj biopandas tensorflow -y
# /opt/conda/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: 
# FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23.
RUN pip install -U "scikit-learn<0.23" rdkit-pypi

# cleanup
RUN apt-get clean
RUN mamba clean --all --yes
RUN pip cache purge

# Install onionnet
RUN git clone https://github.com/cyangNYU/onionnet.git
WORKDIR /onionnet

# Download models
## the default model of onionnet-v1 in github repo is not correct, the actually size is around 600 MB. 
## The authors provided a google drive link to download it, 
## but their command wget "https://drive.google.com/uc?export=download&id=1cwJN44TgaVBWYEEb_SGU5JBJp6WbFdM1" -O "CNN_final_model_weights.h5" is not working.
RUN cd models && rm CNN_final_model_weights.h5 && wget https://huggingface.co/cyangNYU/onionnet-v1/resolve/main/CNN_final_model_weights.h5
ADD Dockerfile_onionnet .
