FROM ubuntu:22.04
RUN apt-get update && apt-get install -y wget
# Download the bdbbind dataset
RUN wget --no-clobber http://www.pdbbind.org.cn/download/PDBbind_v2020_refined.tar.gz
RUN tar -xvf PDBbind_v2020_refined.tar.gz
# Install miniconda
RUN CONDA="Mambaforge-Linux-x86_64.sh" && \
    wget --quiet https://github.com/conda-forge/miniforge/releases/latest/download/$CONDA && \
    chmod +x $CONDA && \
    ./$CONDA -b -p /mambaforge && \
    rm -f $CONDA
ENV PATH /mambaforge/bin:$PATH
RUN mamba install -c conda-forge pandas
ADD generate_pdbbind_complex.py .
ADD Dockerfile_PDBbind_refined .

