name: Receive CI response

on:
  repository_dispatch:

run-name:  "${{ github.event.client_payload.run_name }}"

jobs:
  ci_receive:
    runs-on: ubuntu-latest
    steps:
      - name: Receive CI status from remote repository
        if: github.event.action == 'ci_status'
        run: |
          echo "CI status received from '${{ github.event.client_payload.repository }}'"
          if [ "${{ github.event.client_payload.success }}" = "true" ]; then
            echo "CI run was successful."
          else
            echo "CI run failed."
          fi