name: Send CI request

on:
  push:
  pull_request_target:

jobs:
  ci_send:
    runs-on: ubuntu-latest
    steps:
      # See comments in token.md
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Check actor's identity
        env:
          APP_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          if ! curl -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  -H "Authorization: Bearer $APP_TOKEN" \
                  https://api.github.com/repos/${{ github.repository }}/collaborators \
                  | jq '.[].login' | grep "${{ github.event.sender.login }}";
          then
            echo "Account doesn't have enough permissions!" \
              && false;
          fi

      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Initiating repository dispatch event
        id: initiate_repo_dispatch
        uses: ./.github/my_actions/repository_dispatch/
        with:
          repository: ${{ github.repository }}
          owner: ${{ github.repository_owner }}
          ref: ${{ github.ref_name }}
          commit_message: ${{ github.event.head_commit.message }}
          target_repository: workflow-inference-compiler
          access_token: ${{ steps.generate_token.outputs.token }}