name: Send CI request

on:
  push:
  pull_request_target:

jobs:
  ci_send:
    runs-on: ubuntu-latest
    steps:
      # See comments in token.md
      - name: Generate a token
        if: always()
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Initiating repository dispatch event
        if: github.event_name == 'push'
        id: initiate_repo_dispatch_push
        uses: ./.github/my_actions/repository_dispatch/
        with:
          event_name: ${{ github.event_name }}
          repository: ${{ github.repository }}
          owner: ${{ github.repository_owner }}
          ref_name: ${{ github.ref_name }}
          commit_message: ${{ github.event.head_commit.message }}
          target_repository: workflow-inference-compiler
          access_token: ${{ steps.generate_token.outputs.token }}

      - name: Create environment variables
        if: github.event_name == 'pull_request_target'
        env:
          COMMIT_MESSAGE: ''
        run: |
          echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_ENV

      # Unbelievably, for pull requests only, there is apparently no way to get
      # the commit message directly via the github API.
      # See https://github.com/orgs/community/discussions/28474
      - name: Checkout commit sha (Pull Request only)
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get commit message (Pull Request only)
        if: github.event_name == 'pull_request_target'
        run: |
          echo "commit_message=$(git show -s --format=%s)" >> $GITHUB_ENV

      - name: Initiating repository dispatch event
        if: github.event_name == 'pull_request_target'
        id: initiate_repo_dispatch_pr
        uses: ./.github/my_actions/repository_dispatch/
        with:
          event_name: ${{ github.event_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          owner: ${{ github.event.pull_request.head.repo.owner.login }}
          ref_name: ${{ github.event.pull_request.head.ref }}
          commit_message: ${{ env.commit_message }}
          target_repository: workflow-inference-compiler
          access_token: ${{ steps.generate_token.outputs.token }}