name: Docker Build

on:
  # push:  # Do NOT run on every push!
  # pull_request: (either on origin or on upstream pull request)
  schedule:
  # Run it every Tuesday at midnight.
    - cron: '0 0 * * 2'

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  docker_build:
    strategy:
      fail-fast: false
      matrix:
        # NOTE: Use a matrix (instead of dockerBuild.sh) for parallelism
        dockerfile: [align_protein_ca_mda, align_protein_ca_pymol, atomselect,
                     autodock_vina, autodock_vina_filter, bash_scripts,
                     calculate_net_charge, generate_conformers,
                     mol2_to_pdbqt, nmr4md, openbabel,
                     remove_terminal_residue_name_prefixes,
                     rename_residues, combine_structure,
                     remove_terminal_residue_name_prefixes, molgan,
                     pdbbind_refined, onionnet-sfct, smina, pdbfixer,
                     fix_pdb_atom_column, extract_protein, extract_ligand_protein, generate_conformers,
                     onionnet, combine_pdb]  # No username for pdbind_refined
        # skip data/ and cwl_adapters/file_format_conversions/biosimspace/
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Docker Build scripts/
      run: cd examples/scripts/ && docker build --no-cache --pull -f Dockerfile_${{ matrix.dockerfile }} -t polusai/mm_${{ matrix.dockerfile }} .
