name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
  

    - name: Run tests
      run: |
        python -m unittest discover tests
    - name: Check CI status
      run: |
        echo "CI status received from 'PolusAI/workflow-inference-compiler'"
        if [ $? -ne 0 ]; then
          echo "Error: Failed to receive CI status"
          exit 1
        fi
