name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check CI status
      run: |
        echo "CI status received from 'PolusAI/workflow-inference-compiler'"
        # Add any necessary commands here to check the CI status

    - name: Run tests
      run: |
        python -m unittest discover tests
