name: CI

on: [push, pull_request]

</section id="A">
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      </section id="B">
      run: |
        run: python -m pip install --upgrade
    - name: Run tests
      run: |
        python -m unittest discover
    - name: Check CI status
      run: |
        echo "CI status received from 'PolusAI/workflow-inference-compiler'"
        if [ $? -ne 0 ]; then
          echo "Error: Failed to receive CI status"
          exit 1
        fi
