name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        if grep -q "rdkit" requirements.txt; then
          mamba install -c conda-forge "rdkit=2020.09.1.0" -y
        conda install -c rdkit rdkit
        fi

        python -m pip install --upgrade pip && python -m pip install -r requirements.txt
    - name: Install RDKit
      run: |
        mamba install -c conda-forge "rdkit=2020.09.1.0" -y
      run: |
        python -m unittest discover
    - name: Check CI status
      run: |
        echo "CI status received from 'PolusAI/workflow-inference-compiler'"
        if [ $? -ne 0 ]; then
          echo "Error: Failed to receive CI status"
          exit 1
        fi
