name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: mambaorg/micromamba@0.16.7
      with:
        python: 3.7.*
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        if grep -q "rdkit" requirements.txt; then
          conda install -c rdkit rdkit
        fi

        mamba install -q --yes python=3.7.* numpy=1.19.*
        python -m pip install rdkit==2020.09.1.0
    - name: Run tests
      run: |
        python -m unittest discover
    - name: Check CI status
      run: |
        echo "CI status received from 'PolusAI/workflow-inference-compiler'"
        if [ $? -ne 0 ]; then
          echo "Error: Failed to receive CI status"
          exit 1
        fi
