name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Echo CI status
        run: echo "CI status received from 'PolusAI/workflow-inference-compiler'"

      - name: Deploy to production
        run: |
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            echo "Deploying to production"
            # Add deployment steps here
          fi
