name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check environment and CI status
      run: |
        env
        if [ -f "CI_status.txt" ]; then
          echo "CI status received from 'PolusAI/workflow-inference-compiler'"
        else
          echo "CI_status.txt does not exist"
        fi
