name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: Install dependencies
        run: |
          pip install autopep8 pylint mypy sphinx
    - name: Run tests
      run: |
        python -m unittest discover
    - name: Check CI status
      run: |
        echo "CI status received from 'PolusAI/workflow-inference-compiler'"
        if [ $? -ne 0 ]; then
          echo "Error: Failed to receive CI status"
          exit 1
        fi
